version: "3.9"

services:
  photobooth:
    platform: linux/arm64
    build: .
    volumes:
      - ./:/app
      - /app/resources/css/
      - /app/resources/js/
      - /app/vendor/
    ports:
      - "80:80"
    environment:
      - COMPOSER_VERSION=2
